# Generated by Django 2.1.2 on 2018-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
