# Generated by Django 2.1.2 on 2018-10-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipts_invalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='invalid',
            field=models.IntegerField(default=0),
        ),
    ]
