# Generated by Django 2.1.2 on 2018-10-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipts_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
