# Generated by Django 2.1.2 on 2018-10-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20181024_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
    ]
