# Generated by Django 2.1.2 on 2018-10-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_item_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='receipts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=5000),
        ),
    ]
