# Generated by Django 2.1.2 on 2018-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20181024_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Time')),
            ],
        ),
    ]
