# Generated by Django 2.1.2 on 2018-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_syncinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='user',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
